// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvxW7mOtKT0yjyWnWvTov_igGomvoMpbc',
    appId: '1:974738265062:web:cb5ffee111d4edf454fc27',
    messagingSenderId: '974738265062',
    projectId: 'puebly-app',
    authDomain: 'puebly-app.firebaseapp.com',
    storageBucket: 'puebly-app.appspot.com',
    measurementId: 'G-L2NELQR7TT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqDudSo2dOM1yPpdhuBUQKTPth9fTd0tg',
    appId: '1:974738265062:android:560ca7dadd73016154fc27',
    messagingSenderId: '974738265062',
    projectId: 'puebly-app',
    storageBucket: 'puebly-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD43P2TB1josVM_sEKgibdnYg9Cs143dus',
    appId: '1:974738265062:ios:1b5881fe0f84020854fc27',
    messagingSenderId: '974738265062',
    projectId: 'puebly-app',
    storageBucket: 'puebly-app.appspot.com',
    iosBundleId: 'com.example.puebly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD43P2TB1josVM_sEKgibdnYg9Cs143dus',
    appId: '1:974738265062:ios:7ebfaf59d8acc35e54fc27',
    messagingSenderId: '974738265062',
    projectId: 'puebly-app',
    storageBucket: 'puebly-app.appspot.com',
    iosBundleId: 'com.example.puebly.RunnerTests',
  );
}
